# Generated by Django 2.1.1 on 2018-10-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servo', '0002_auto_20180925_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'get_latest_by': 'id', 'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='repair',
            name='issue_code',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='repair',
            name='symptom_code',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
